### PR TITLE
Cash register

### PR DESCRIPTION
**Pull request by Hasinarahman**
Creating cash register by using html, css and js.
cash register

### CODE REVIEW

**Comment by Hasinarahman** [comment]
Hello @Najeeba-Qarqin
please check my project.

**Comment by Najeeba-Qarqin** [comment]
Hi @Hasinarahman 🙋‍♀️
Well done your project is great.
You followed GitHub workflows. 
Your code passes the free code camp test. 
Your repo have professional Readme file.
Your PR is descriptive. 
Your project is responsive design. 
You implemented beautifull design. 
Your project is approved you can mention the mentor.

**Comment by Hasinarahman** [comment]
hello sir @ahzamir
please check my project.

**Review by ahzamir — APPROVED** [review]
### Hi @Hasinarahman 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- Well done your code functions well and also passed the freecodecamp checks.

- [OPTIONAL] - You have to show the user the total amount so the user knows how much he/she should pay.

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Cash Register project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by Hasinarahman** [comment]
ok thanks teacher
@ahzamir

**Pull request merged**
